[deploy]
bucket = 'nwaliechinyere-cfn-artifacts'
region = 'us-east-1'
stack_name = 'CrdSyncRole'

[parameters]
GitHubOrg = 'Chinyere-nwalie'
RepositoryName = 'aws-bootcamp-cruddur-2023'
OIDCProviderArn = ''